spring:
  datasource:
    url: jdbc:mysql://database:3306/multijobs
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp:
          use_jdbc_metadata_defaults: false
      ddl-auto: none